version: "3.9"

services:
  #    kong:
  #        image: kong/kong-gateway:3.2.1.0
  #        ports:
  #            - "8000:8000"
  #            - "8443:8443"
  #            - "8001:8001"
  #            - "8444:8444"
  #        environment:
  #            KONG_DATABASE: "postgres"
  #            KONG_PG_HOST: "postgres"
  #            KONG_PG_USER: "kong"
  #            KONG_PG_PASSWORD: "kong"
  #            KONG_PG_DATABASE: "kong"
  ##        volumes:
  ##            - ./kong.yml:/usr/local/kong/declarative/kong.yml
  #        depends_on:
  #            - postgres
  #    postgres:
  #        image: postgres:13
  #        environment:
  #            POSTGRES_USER: "kong"
  #            POSTGRES_PASSWORD: "kong"
  #            POSTGRES_DB: "kong"
  nginx:
    build:
      context: .
    image: nginx:1.23.3
    restart: always
    networks:
      app_net:
        ipv4_address: 172.12.1.10
    ports:
      - "8000:80"
    #      - "8443:443"
    volumes:
      - ${APP_ROOT}:/var/www/html/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - php
  php:
    image: fpm:8028
    #        build:
    #            context: /Users/dannylee/Documents/works/railway-admin
    #            dockerfile: ./phpfpm/Dockerfile
    restart: always
    volumes:
      - ${APP_ROOT}:/var/www/html/
      - ./phpfpm/php.ini:/usr/local/etc/php/php.ini
      - ./phpfpm/conf.d/docker-php-ext-opcache.ini:/usr/local/etc/php/conf.d/docker-php-ext-opcache.ini
      - ./phpfpm/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./phpfpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      app_net:
        ipv4_address: 172.12.1.20

  #  hyperf:
  #    image: hf:latest
  #    build:
  #      context: .
  #      dockerfile: ./images/hyperf/Dockerfile
  #    restart: always
  #    volumes:
  #      - /Users/dannylee/Documents/works/railway-api/:/var/www/
  #    ports:
  #      - "19501:9501"
  #    networks:
  #      app_net:
  #        ipv4_address: 172.12.1.30

  redis:
    image: redis/redis-stack:latest
    restart: always
    ports:
      - "26379:6379"
      - "28001:8001"
    networks:
      app_net:
        ipv4_address: 172.12.1.40

  #    postgresql:
  #        image: postgres:latest
  #        volumes:
  #            - ./data/postgres_data:/var/lib/postgresql/data
  #            - pgdata:/var/lib/postgresql/data
  #        restart: always
  #        environment:
  #            POSTGRES_USER: 'postgres'
  #            POSTGRES_PASSWORD: 'fuck123sql'
  #            PGDATA: /var/lib/postgresql/data/pgdata
  #        ports:
  #            - "10020:5432"
  #        networks:
  #            app_net:
  #                ipv4_address: 172.12.1.50

  #    pgbouncer:
  #        image: bitnami/pgbouncer:latest
  #        volumes:
  #            - /path/to/init-scripts:/docker-entrypoint-initdb.d
  #        networks:
  #            app_net:
  #                ipv4_address: 172.12.1.60

  #    pgadmin:
  #        image: dpage/pgadmin4:latest
  #        restart: always
  #        environment:
  #            PGADMIN_DEFAULT_EMAIL: 'a@a.com'
  #            PGADMIN_DEFAULT_PASSWORD: 'fuck123sql'
  #        ports:
  #            - "10021:80"
  #        networks:
  #            app_net:
  #                ipv4_address: 172.12.1.70

  #  CREATE USER 'root'@'%' IDENTIFIED BY 'fuck123sql';
  #  GRANT ALL PRIVILEGES ON *.* TO 'root'@'%';
  #  FLUSH PRIVILEGES;
  mysql:
    image: bitnami/mysql
    volumes:
      #      - ./mysql/my.cnf:/etc/my.cnf
      #      - ./mysql/mysql-data:/var/lib/mysql
      - ./mysql/bitnami.my.cnf:/opt/bitnami/mysql/conf/my.cnf
      - ./mysql/data:/bitnami/mysql/data
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'fuck123sql'
      MYSQL_ROOT_HOST: '0.0.0.0'
      MYSQL_MAX_CONNECTIONS: 200
    user: root
    ports:
      - "33061:3306"
    networks:
      app_net:
        ipv4_address: 172.12.1.80

  #    zinc:
  #        image: public.ecr.aws/zinclabs/zinc:latest
  #        restart: always
  #        environment:
  #            ZINC_FIRST_ADMIN_USER: 'root'
  #            ZINC_FIRST_ADMIN_PASSWORD: 'fuck123sql'
  #        ports:
  #            - "14080:4080"
  #        networks:
  #            app_net:
  #                ipv4_address: 172.12.1.90

  #  elasticsearch:
  #    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.0
  #    environment:
  #      - xpack.security.enabled=false
  #      - discovery.type=single-node
  #    ulimits:
  #      memlock:
  #        soft: -1
  #        hard: -1
  #      nofile:
  #        soft: 65536
  #        hard: 65536
  #    cap_add:
  #      - IPC_LOCK
  #    volumes:
  #      - ./data/es-data:/usr/share/elasticsearch/data
  #    ports:
  #      - "19200:9200"
  #      - "19300:9300"
  #    networks:
  #      app_net:
  #        ipv4_address: 172.12.1.100
  #
  #  kibana:
  #    image: docker.elastic.co/kibana/kibana:8.6.0
  #    environment:
  #      - ELASTICSEARCH_HOSTS=http://172.12.1.100:9200
  #    ports:
  #      - "15601:5601"
  #    depends_on:
  #      - elasticsearch
  #    networks:
  #      app_net:
  #        ipv4_address: 172.12.1.110

  #  Etcd:
  #    image: bitnami/etcd:latest
  #    environment:
  #      - ALLOW_NONE_AUTHENTICATION=yes
  #      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
  #    ports:
  #      - "2379:2379"
  #      - "2380:2380"
  #    networks:
  #      app_net:
  #        ipv4_address: 172.12.1.120

#  nacos:
#    image: nacos/nacos-server:latest
#    ports:
#      - "18848:8848"
#    environment:
#      MODE: standalone
#    networks:
#      app_net:
#        ipv4_address: 172.12.1.130

volumes:
  pgdata:
  es_data:
    driver: local

networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: 172.12.1.0/16
